### ISSUE TITLE
1.12 compatibility

### ISSUE THREAD

**Issue by GriffinCodes** [diecode/KillerMoney#10]
```
[20:29:14] [Server thread/INFO]: [KillerMoney] Enabling KillerMoney v4.0.2
[20:29:14] [Server thread/WARN]: [KillerMoney] Invalid message method value. Using default "CHAT" value.
[20:29:14] [Server thread/ERROR]: Error occurred while enabling KillerMoney v4.0.2 (Is it up to date?)
java.lang.NullPointerException: null
        at net.diecode.killermoney.configs.DefaultConfig.load(DefaultConfig.java:91) ~[?:?]
        at net.diecode.killermoney.configs.DefaultConfig.<init>(DefaultConfig.java:44) ~[?:?]
        at net.diecode.killermoney.BukkitMain.onEnable(BukkitMain.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-6629162-cda27c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```
See [spigot's homepage](https://spigotmc.org) for information regarding the 1.12 pre-release

Also, I am using [MVdW](https://www.spigotmc.org/resources/authors/maximvdw.6687/)'s plugins ([FeatherBoard](https://www.spigotmc.org/resources/featherboard.2691/), [ActionBar](https://www.spigotmc.org/resources/actionbar.1458/), etc), and they are throwing this error on startup:
```
[20:28:32] [Server thread/ERROR]: [Tab] java.lang.NoClassDefFoundError: net/diecode/KillerMoney/KillerMoneyAPI
        at be.maximvdw.tabcore.placeholders.Z.initialize(KillerMoneyPlaceholder.java:140)
        at be.maximvdw.tabcore.placeholders.Placeholder.registerPlaceHolder(Placeholder.java:2256)
        at be.maximvdw.tabcore.placeholders.Z.<init>(KillerMoneyPlaceholder.java:135)
        at be.maximvdw.tabcore.placeholders.aC.a(PlaceholderLoader.java:474)
        at be.maximvdw.tab.Tab.initPlaceholders(Unknown Source)
        at be.maximvdw.tab.Tab.loadConfiguration(Unknown Source)
        at be.maximvdw.tabcore.BasePlugin.initialize(Unknown Source)
        at be.maximvdw.tabcore.BasePlugin.onEnable(Unknown Source)
        at be.maximvdw.tab.Tab.onEnable(Unknown Source)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326)
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.diecode.KillerMoney.KillerMoneyAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more
```
I'd imagine that's some recent change you made, but it might be on MVdW's end. Can you confirm?

**Comment by kgahor** [comment]
Hey,

I think you are using old killermoney's configs. Please delete plugin/KillerMoney directory and restart server.

I didn't finish KillerMoney v4 API yet, so the API is broken atm.

**Comment by GoldenLizardYT** [comment]
@diecode  I think this glitch is happening with everyone, not just my server-
When I do /km help, it tells me to do it again.
I can't do any of the other KM commands, and its definitely not a perms issue.
The console also isn't displaying anything related to the command...
Please see if there are any problems with this, thank you!

**Comment by kgahor** [comment]
The 4.1.0 is supported 1.12.
