### ISSUE TITLE
PlayerPickupItemEvent

### ISSUE THREAD

**Issue by Benkers** [diecode/KillerMoney#11]
Recently there has been an update with the way the PlayerPickupItemEvent is handled and this has caused your plugin to print warnings on startup:

`
[07:02:59 INFO]: [KillerMoney] Enabling KillerMoney v4.0.2
[07:02:59 WARN]: [KillerMoney] "KillerMoney v4.0.2" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public v
oid net.diecode.killermoney.functions.MoneyHandler.onItemPickUp(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Serv
er performance will be affected"; please notify the authors [diecode].
org.bukkit.plugin.AuthorNagException: null
        at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:285) [patched_1.12.jar:git-Paper-1168]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:545) [patched_1.12.jar:git-Paper-1168]
        at net.diecode.killermoney.BukkitMain.onEnable(BukkitMain.java:101) [KillerMoney-4.0.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.jar:git-Paper-1168]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1168]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1168]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [patched_1.12.jar:git-Paper-1168]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1168]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1168]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
`

If the above is hard to read, you can view the error here: https://hastebin.com/upovakulew.css

I'd appreciate if you could fix this.

Thank you, Ben.

**Comment by kgahor** [comment]
I will use other method in the future, but I don't want break the version compatibility atm. This error will not affect your server performance.

**Comment by kgahor** [comment]
This is not causing problem
