### ISSUE TITLE
Custom-item-drop

### ISSUE THREAD

**Issue by florosss** [diecode/KillerMoney#34]
hello i would like to add Custom-item-drop EXPERIENCE_BOTTLE but it does not work

Custom-item-drop:
Enabled: true
Keep-default-items: true
Items:
'1':
ItemStack:
==: org.bukkit.inventory.ItemStack
type: EXPERIENCE_BOTTLE
Random-amount: 1 ? 2
Chance: 100%

27.10 22:05:50 [Server] INFO [KillerMoney] Enabling KillerMoney v4.4.0*
27.10 22:05:50 [Server] ERROR [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
27.10 22:05:50 [Server] INFO java.lang.IllegalArgumentException: Material cannot be null
27.10 22:05:50 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:493) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
27.10 22:05:50 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
27.10 22:05:50 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
27.10 22:05:50 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
27.10 22:05:50 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[patched_1.14.4.jar:git-Paper-214]
27.10 22:05:50 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[patched_1.14.4.jar:git-Paper-214]

**Comment by Intrigger** [comment]
Hi! Have you solved the problem? I have the same problem, i think its smth wrong with documentaion cause I made everything just like the developer said...
