### ISSUE TITLE
Issue with 4.0.0

### ISSUE THREAD

**Issue by appsbytom** [diecode/KillerMoney#7]
So i have tried to use this and when the mob is killed the console is spammed with 

[18:55:56 ERROR]: Could not pass event EntityDeathEvent to KillerMoney v4.0.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:363) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityLiving.die(EntityLiving.java:868) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:806) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityHuman.attack(EntityHuman.java:1002) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityPlayer.attack(EntityPlayer.java:1051) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1312) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-550ebace-7019900e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-550ebace-7019900e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ArrayIndexOutOfBoundsException

Any help would be great.

**Comment by kgahor** [comment]
Did you use previously version from KillerMoney? If yes, did you remove the config.yml before you installed the 4.0.0?

**Comment by appsbytom** [comment]
I copied the example from the github entities setup and its completely different too what the config generates is. i think the example is out of date

**Comment by kgahor** [comment]
No it isn't. Can you paste here your config.yml file?

**Comment by appsbytom** [comment]
Ok its fine now. I sorted it.

**Comment by kgahor** [comment]
Great! :)

**Comment by appsbytom** [comment]
I found what was causing it, When i turned the Run-method too RANDOM, when a entity is killed the error message appears. nothing was changed but the RANDOM. on 1.8 so maybe thats it
