### ISSUE TITLE
Issue with adding item drops

### ISSUE THREAD

**Issue by appsbytom** [diecode/KillerMoney#9]
[16:06:22 ERROR]: Cannot load plugins\KillerMoney\entities.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 114, column 35:
                                amount: 32
                                      ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.diecode.killermoney.managers.ConfigManager.reload(ConfigManager.java:53) [KillerMoney.jar:?]
        at net.diecode.killermoney.configs.EntitiesConfig.load(EntitiesConfig.java:31) [KillerMoney.jar:?]
        at net.diecode.killermoney.commands.subcommands.ReloadCommand.run(ReloadCommand.java:25) [KillerMoney.jar:?]
        at net.diecode.killermoney.commands.KMCommand.onCommand(KMCommand.java:85) [KillerMoney.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-550ebace-7019900e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 114, column 35:
                                amount: 32
                                      ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        ... 16 more
[16:06:22 INFO]: Configs are reloaded

Thats the error I get when trying to add items. Heres the entities part where i edited.

                '3':
                    ItemStack:
                        ==: org.bukkit.inventory.ItemStack
                        type: GOLD_INGOT
                            amount: 32
                            meta: 
                              ==: ItemMeta
                              meta-type: UNSPECIFIC
                              display-name: "§rAmazing gold ingot"
                              lore:
                              - "Nicest"
                    Random-amount: 1 ? 20
                    Chance: 100%
                    Permission: 'km.custom.permission'
                    Limit: 100

**Comment by kgahor** [comment]
This is my fault with docs, sorry. Try this please:

```yaml
==: org.bukkit.inventory.ItemStack
type: GOLD_INGOT
amount: 32
meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: "§cAmazing gold ingot"
    lore:
    - "§2Nicest"
```
